name: Build and Deploy Next.js

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  pull_request:
    branches:
      - master
      - development
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      run: npm install

    - name: Build Project
      run: npm run build

  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Set the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Add your Render API Key as a GitHub Secret
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}  # Add your Render Service ID as a GitHub Secret
          BRANCH_NAME: ${{ github.ref }}  # Automatically set to the branch that triggered the workflow
        run: |
          # Extract the branch name from the ref (e.g., refs/heads/branch-name -> branch-name)
          BRANCH_NAME=${GITHUB_REF#refs/heads/}

          # Trigger Render deployment for the current branch
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{
              "branch": "'"$BRANCH_NAME"'"
            }'

